### ISSUE TITLE
Restore does not fail gracefully when file not found

### ISSUE THREAD

**Issue by tamsingreen** [localz/consul-backup-restore#4]
When trying to restore from a local file that does not exist, the following error is logged and the program exits:

```
{ Error: ENOENT: no such file or directory, open 'path/to/backup'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'path/to/backup' }
/consul/consul-config-server/node_modules/consul-backup-restore/src/consulUtil.js:28
  var keyValues = JSON.parse(rawData.toString('utf-8'))
                                    ^

TypeError: Cannot read property 'toString' of undefined
    at Object.exports.restoreKeyValues (/consul/consul-config-server/node_modules/consul-backup-restore/src/consulUtil.js:28:37)
    at ReadFileContext.fs.readFile [as callback] (/consul/consul-config-server/node_modules/consul-backup-restore/src/consulBackupRestore.js:61:18)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
```

**Comment by tamsingreen** [comment]
I've opened a PR with a patch here: https://github.com/localz/consul-backup-restore/pull/5

**Comment by nathanmalishev** [comment]
Looks good.
Thanks - merged https://github.com/localz/consul-backup-restore/pull/5
